# Default options for compare_matching.py

dataset: ./assets/matching/crop_1350x1012/
cuda_sift_dataset: ./assets/matching/no_crop_1440x1080

downscale: 1

lightglue_filter_threshold: 0.05
lightglue_depth_confidence: -1
lightglue_width_confidence: -1

sift_max_keypoints: 5000
sift_contrast_threshold: 0.0
sift_edge_threshold: 10.0
sift_n_octave_layers: 10

disk_max_keypoints: 5000
disk_detection_threshold: 0.0
aliked_model_name: aliked-t16
aliked_max_keypoints: 5000
aliked_detection_threshold: 0.0

nn_match_threshold: null
ratio_nn_thresh: null


superpoint_model_name: MagicLeap
superpoint_weights_path: ./weights/MagicLeap/superpoint_v1.pth
superpoint_max_keypoints: 5000
superpoint_detection_threshold: 0.0005

device: cuda
